[workspace]
members = [
    "boot",
    "brain",
    "brain/macros",
    "btle",
    "btle/pi_test",
    "cache",
    "console",
    "core",
    "gpio",
    "interrupt",
    "lock",
    "mailbox",
    "register",
    "singleton",
    "timer",
    "uart"
]